# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'print_fragment_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PrintFragmentDialogBase(object):
    def setupUi(self, PrintFragmentDialogBase):
        PrintFragmentDialogBase.setObjectName("PrintFragmentDialogBase")
        PrintFragmentDialogBase.resize(395, 614)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PrintFragmentDialogBase.sizePolicy().hasHeightForWidth())
        PrintFragmentDialogBase.setSizePolicy(sizePolicy)
        PrintFragmentDialogBase.setMinimumSize(QtCore.QSize(0, 0))
        PrintFragmentDialogBase.setMaximumSize(QtCore.QSize(5000, 5000))
        PrintFragmentDialogBase.setSizeGripEnabled(False)
        PrintFragmentDialogBase.setModal(False)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(PrintFragmentDialogBase)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radio_shablonPrint = QtWidgets.QRadioButton(PrintFragmentDialogBase)
        self.radio_shablonPrint.setObjectName("radio_shablonPrint")
        self.verticalLayout_6.addWidget(self.radio_shablonPrint)
        self.groupBox_ShablonPrint = QtWidgets.QGroupBox(PrintFragmentDialogBase)
        self.groupBox_ShablonPrint.setTitle("")
        self.groupBox_ShablonPrint.setCheckable(False)
        self.groupBox_ShablonPrint.setChecked(False)
        self.groupBox_ShablonPrint.setObjectName("groupBox_ShablonPrint")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_ShablonPrint)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_ShablonPrint)
        self.comboBox_3.setMaxVisibleItems(30)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_10.addWidget(self.comboBox_3)
        self.verticalLayout_6.addWidget(self.groupBox_ShablonPrint)
        self.line_3 = QtWidgets.QFrame(PrintFragmentDialogBase)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.radio_userPrint = QtWidgets.QRadioButton(PrintFragmentDialogBase)
        self.radio_userPrint.setObjectName("radio_userPrint")
        self.verticalLayout_6.addWidget(self.radio_userPrint)
        self.groupBox_userPrint = QgsCollapsibleGroupBox(PrintFragmentDialogBase)
        self.groupBox_userPrint.setTitle("")
        self.groupBox_userPrint.setCheckable(False)
        self.groupBox_userPrint.setChecked(False)
        self.groupBox_userPrint.setObjectName("groupBox_userPrint")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_userPrint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_Headers = QgsCollapsibleGroupBox(self.groupBox_userPrint)
        self.groupBox_Headers.setCheckable(True)
        self.groupBox_Headers.setChecked(False)
        self.groupBox_Headers.setCollapsed(False)
        self.groupBox_Headers.setObjectName("groupBox_Headers")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_Headers)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(1)
        self.formLayout.setObjectName("formLayout")
        self.label_12 = QtWidgets.QLabel(self.groupBox_Headers)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_Headers)
        self.comboBox.setMaxVisibleItems(20)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_11 = QtWidgets.QLabel(self.groupBox_Headers)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_Headers)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_4 = QtWidgets.QLabel(self.groupBox_Headers)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_Headers)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.verticalLayout_7.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox_Headers)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_userPrint)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.spinBox_scale = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_scale.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_scale.setMaximum(1000000)
        self.spinBox_scale.setSingleStep(100)
        self.spinBox_scale.setProperty("value", 2000)
        self.spinBox_scale.setObjectName("spinBox_scale")
        self.horizontalLayout_3.addWidget(self.spinBox_scale)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.checkBox_Frame = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Frame.setChecked(False)
        self.checkBox_Frame.setObjectName("checkBox_Frame")
        self.verticalLayout_3.addWidget(self.checkBox_Frame)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_userPrint)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_9.setContentsMargins(-1, 1, -1, 7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.spinBox_Top = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_Top.setMaximum(500)
        self.spinBox_Top.setProperty("value", 10)
        self.spinBox_Top.setObjectName("spinBox_Top")
        self.gridLayout.addWidget(self.spinBox_Top, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.spinBox_Right = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_Right.setMaximum(500)
        self.spinBox_Right.setProperty("value", 10)
        self.spinBox_Right.setObjectName("spinBox_Right")
        self.gridLayout.addWidget(self.spinBox_Right, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.spinBox_Left = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_Left.setMaximum(500)
        self.spinBox_Left.setProperty("value", 10)
        self.spinBox_Left.setObjectName("spinBox_Left")
        self.gridLayout.addWidget(self.spinBox_Left, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 2, 1, 1)
        self.spinBox_Bottom = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_Bottom.setMaximum(500)
        self.spinBox_Bottom.setProperty("value", 10)
        self.spinBox_Bottom.setObjectName("spinBox_Bottom")
        self.gridLayout.addWidget(self.spinBox_Bottom, 1, 3, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_Legend = QgsCollapsibleGroupBox(self.groupBox_userPrint)
        self.groupBox_Legend.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_Legend.setStyleSheet("QgsCollapsibleGroupBoxBasic::title, QgsCollapsibleGroupBox::title {  subcontrol-origin: margin;  subcontrol-position: top left;  margin-left: 20px;  margin-right: 5px;  left: 0px;  top: 2px;}")
        self.groupBox_Legend.setCheckable(True)
        self.groupBox_Legend.setChecked(False)
        self.groupBox_Legend.setCollapsed(False)
        self.groupBox_Legend.setSaveCheckedState(False)
        self.groupBox_Legend.setObjectName("groupBox_Legend")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_Legend)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_legenduser = QtWidgets.QRadioButton(self.groupBox_Legend)
        self.radioButton_legenduser.setChecked(True)
        self.radioButton_legenduser.setObjectName("radioButton_legenduser")
        self.verticalLayout_5.addWidget(self.radioButton_legenduser)
        self.frame_user = QtWidgets.QFrame(self.groupBox_Legend)
        self.frame_user.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_user.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_user.setObjectName("frame_user")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_user)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line_2 = QtWidgets.QFrame(self.frame_user)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.checkBox_Layer_Header = QtWidgets.QCheckBox(self.frame_user)
        self.checkBox_Layer_Header.setObjectName("checkBox_Layer_Header")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox_Layer_Header)
        self.spinBox = QtWidgets.QSpinBox(self.frame_user)
        self.spinBox.setMaximum(200)
        self.spinBox.setProperty("value", 70)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_5 = QtWidgets.QLabel(self.frame_user)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.verticalLayout_5.addWidget(self.frame_user)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.line = QtWidgets.QFrame(self.groupBox_Legend)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.radioButton_legendauto = QtWidgets.QRadioButton(self.groupBox_Legend)
        self.radioButton_legendauto.setChecked(False)
        self.radioButton_legendauto.setObjectName("radioButton_legendauto")
        self.verticalLayout_8.addWidget(self.radioButton_legendauto)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        spacerItem3 = QtWidgets.QSpacerItem(87, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.groupBox_Legend)
        self.verticalLayout_6.addWidget(self.groupBox_userPrint)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/_PrintTools/comp_print/icons/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.button_box = QtWidgets.QDialogButtonBox(PrintFragmentDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.horizontalLayout_8.addWidget(self.button_box)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(7)
        font.setItalic(True)

        self.retranslateUi(PrintFragmentDialogBase)
        self.button_box.accepted.connect(PrintFragmentDialogBase.accept)
        self.button_box.rejected.connect(PrintFragmentDialogBase.reject)
        self.radioButton_legenduser.toggled['bool'].connect(self.frame_user.setEnabled)
        self.radio_userPrint.toggled['bool'].connect(self.groupBox_userPrint.setEnabled)
        self.radio_shablonPrint.toggled['bool'].connect(self.groupBox_ShablonPrint.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(PrintFragmentDialogBase)
        PrintFragmentDialogBase.setTabOrder(self.groupBox_ShablonPrint, self.comboBox_3)
        PrintFragmentDialogBase.setTabOrder(self.comboBox_3, self.comboBox)
        PrintFragmentDialogBase.setTabOrder(self.comboBox, self.comboBox_2)
        PrintFragmentDialogBase.setTabOrder(self.comboBox_2, self.lineEdit_2)
        PrintFragmentDialogBase.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        PrintFragmentDialogBase.setTabOrder(self.lineEdit_3, self.radioButton)
        PrintFragmentDialogBase.setTabOrder(self.radioButton, self.radioButton_2)
        PrintFragmentDialogBase.setTabOrder(self.radioButton_2, self.spinBox)

    def retranslateUi(self, PrintFragmentDialogBase):
        _translate = QtCore.QCoreApplication.translate
        PrintFragmentDialogBase.setWindowTitle(_translate("PrintFragmentDialogBase", "Печать фрагмента карты"))
        self.radio_shablonPrint.setText(_translate("PrintFragmentDialogBase", "Печать из шаблона"))
        self.radio_userPrint.setText(_translate("PrintFragmentDialogBase", "Ручные настройки печати"))
        self.groupBox_Headers.setTitle(_translate("PrintFragmentDialogBase", "Заголовки"))
        self.label_12.setText(_translate("PrintFragmentDialogBase", "Шаблон"))
        self.comboBox.setToolTip(_translate("PrintFragmentDialogBase", "Предустановленные заголовки при необходимости"))
        self.label_11.setText(_translate("PrintFragmentDialogBase", "Заголовок"))
        self.lineEdit_4.setToolTip(_translate("PrintFragmentDialogBase", "Текст заголовка при необходимости"))
        self.label_4.setText(_translate("PrintFragmentDialogBase", "Подзаголовок"))
        self.lineEdit_5.setToolTip(_translate("PrintFragmentDialogBase", "Текст подзаголовка при необходимости"))
        self.groupBox.setTitle(_translate("PrintFragmentDialogBase", "Формат листа"))
        self.comboBox_2.setToolTip(_translate("PrintFragmentDialogBase", "Размер листа бумаги"))
        self.label_3.setText(_translate("PrintFragmentDialogBase", "х"))
        self.spinBox_scale.setPrefix(_translate("PrintFragmentDialogBase", "Масштаб: "))
        self.checkBox_Frame.setToolTip(_translate("PrintFragmentDialogBase", "Отдельная рамка в виде прозрачного прямоугольника вместо встроенной рамки карты. Позволяет в макете наносить маску под рамкой."))
        self.checkBox_Frame.setText(_translate("PrintFragmentDialogBase", "Отдельная рамка"))
        self.groupBox_2.setTitle(_translate("PrintFragmentDialogBase", "Ориентация бумаги"))
        self.radioButton.setText(_translate("PrintFragmentDialogBase", "Вертикальная"))
        self.radioButton_2.setText(_translate("PrintFragmentDialogBase", "Горизонтальная"))
        self.groupBox_6.setTitle(_translate("PrintFragmentDialogBase", "Поля"))
        self.label_6.setText(_translate("PrintFragmentDialogBase", "Верхнее"))
        self.label_9.setText(_translate("PrintFragmentDialogBase", "Правое"))
        self.label_7.setText(_translate("PrintFragmentDialogBase", "Левое"))
        self.label_10.setText(_translate("PrintFragmentDialogBase", "Нижнее"))
        self.groupBox_Legend.setTitle(_translate("PrintFragmentDialogBase", "Легенда"))
        self.radioButton_legenduser.setToolTip(_translate("PrintFragmentDialogBase", "Легенда, разбитая на отдельные элементы по слоям."))
        self.radioButton_legenduser.setText(_translate("PrintFragmentDialogBase", "Пользовательская"))
        self.checkBox_Layer_Header.setText(_translate("PrintFragmentDialogBase", "Подгруппы"))
        self.spinBox.setToolTip(_translate("PrintFragmentDialogBase", "Размер места, отведенного под легенду, внизу листа."))
        self.label_5.setText(_translate("PrintFragmentDialogBase", "Размер легенды (мм)"))
        self.radioButton_legendauto.setToolTip(_translate("PrintFragmentDialogBase", "Встроенная легенда как один элемент макета."))
        self.radioButton_legendauto.setText(_translate("PrintFragmentDialogBase", "QGIS"))

from qgis.gui import QgsCollapsibleGroupBox
